export enum CashMovementCategory {
  COBRO_CLIENTE = 'COBRO_CLIENTE',
  PRESTAMO = 'PRESTAMO',
  ENTRADA_GERENCIA = 'ENTRADA_GERENCIA',
  GASTO_PROVEEDOR = 'GASTO_PROVEEDOR',
  OTRO = 'OTRO',
  TRANSFERENCIA = 'TRANSFERENCIA',
}
